baseURL = "https://lispysnake.com/"
languageCode = "en-us"
title = "Lispy Snake, Ltd."

[params]

    CompanyRegistration = "12179508"
    CompanyAddress = "International House, 24 Holborn Viaduct, London, United Kingdom, EC1A 2BN"

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = true

[taxonomies]
    author = "authors"
    tag = "tags"
    category = "categories"
