baseURL = "https://lispysnake.com/"
languageCode = "en-us"
title = "Lispy Snake, Ltd."

[params]

    CompanyRegistration = "12179508"
    CompanyAddress = "International House, 24 Holborn Viaduct, London, United Kingdom, EC1A 2BN"
